name: External Semantic Layer Sync
run-name: ${{ github.actor }} is uploading an external semantic layer 🚀
on: [push]
jobs:
  External-Semantic-Layer-Sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Archive repository
      run: git archive -o repo.zip HEAD

    - name: Instll jq
      run: sudo apt-get install -y jq

    - name: Send arc hive via curl
      run: |
        response=$(curl -X POST \
          -F "data=@repo.zip" \
          -F "syntax=LOOK_ML" \
          -F "dataConnectionId=fb0b77fd-9213-477d-8e6d-6af40bd3cb39" \
          -F "verbose=true" \
          https://rc.hex.tech/api/v1/semantic-layer \
          -H "Authorization: Bearer 0f2f1643c134f06e362eb0c0ecee0da9b9950bcecdd4e6c17ea2d08981048594521be2bbc209c5ad06485feb58f9ac52"
        
        status_code="${response: -3}"
        if [ "$status_code" -ne 201 ]; then
          echo "Error: Received status code $status_code"
          echo "Response Body:"
          echo -e $(cat response_body.json)
          exit 1
        fi

        echo "✅ Successfully uploaded semantic layer. See below for skipped entities due to currently unsupported features"
        cat response_body.json | jq '.skipped'